PACKAGENAME=persbib
BINARIES=persbib.cls german-pb.lbx
SOURCES=$(PACKAGENAME).dtx $(PACKAGENAME).ins
DOC=$(PACKAGENAME).dvi $(PACKAGENAME).pdf example.pdf

INSTALLDIR=`kpsexpand '$${TEXMFHOME}'/tex/latex/persbib`

default : $(DOC) $(BINARIES)
dist : $(PACKAGENAME).zip


install: $(PACKAGENAME).tds.zip 
	unzip -d $(INSTALLDIR) $^ 
	texhash

BINDIR=texmf/tex/latex/$(PACKAGENAME)
DOCDIR=texmf/doc/latex/$(PACKAGENAME)
SRCDIR=texmf/source/latex/$(PACKAGENAME)

persbib.dvi: persbib.dtx persbib.cls

persbib.pdf: persbib.dtx persbib.cls

example.pdf : example.tex persbib.cls


$(PACKAGENAME).tds.zip : $(BINARIES) $(SOURCES) $(DOC)
	-install -d $(BINDIR) $(SRCDIR) $(DOCDIR)
	install -m 644 $(BINARIES) $(BINDIR)
	install -m 644 $(DOC) $(DOCDIR)
	install -m 644 $(SOURCES) $(SRCDIR)
	cd texmf && zip -mr ../$@ *
	rmdir texmf

$(PACKAGENAME).zip : $(SOURCES) persbib.tds.zip $(PACKAGENAME).pdf
	-mkdir $(PACKAGENAME)
	-install -m 644 $^ $(PACKAGENAME)
	zip -mr $@ $(PACKAGENAME)



## Remove everything generated by this makefile
maintainerclean: cleanall
	-rm $(BINARIES) $(PACKAGENAME).ins $(PACKAGENAME).install $(PACKAGENAME).zip $(PACKAGENAME).tds.zip

## Remove temporary files as well as typeset documentation
cleanall : clean
	-rm $(PACKAGENAME).dvi $(PACKAGENAME).pdf

## Remove temporary files
clean : 
	-rm $(PACKAGENAME).aux $(PACKAGENAME).bcf $(PACKAGENAME).glo $(PACKAGENAME).hd $(PACKAGENAME).idx $(PACKAGENAME).log $(PACKAGENAME).out $(PACKAGENAME).run.xml


## Extract the installer from the dtx file
%.preins :
	echo '\\input docstrip' > $@
	echo '\\askforoverwritefalse' >> $@
	echo '\\generate{\\file{$*.ins}{\\from{$*.dtx}{installer}}}' >> $@
	echo '\\endbatchfile' >> $@

%.ins : %.preins %.dtx
	tex $<

# Extract binaries from the bundle
$(BINARIES) : $(PACKAGENAME).ins $(PACKAGENAME).dtx
	latex $<

%.pdf : %.dtx
	pdflatex $<
	-[ -r $*.glo ] && makeindex $*.glo
	-[ -r $*.idx ] && makeindex $*.idx
	-[ -r $*.bcf ] && biber $*.bcf
	pdflatex $<


%.pdf : %.tex
	pdflatex $<
	-[ -r $*.glo ] && makeindex $*.glo
	-[ -r $*.idx ] && makeindex $*.idx
	-[ -r $*.bcf ] && biber $*.bcf
	pdflatex $<

%.dvi : %.dtx
	latex $<
	makeindex $*.glo
	makeindex $*.idx
	latex $<

